In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({
    "Diameter": [8, 10, 12],
    "Price": [10, 13, 16]
})

In [4]:
mean_x,mean_y= df.mean(axis= 0 )["Diameter"],df.mean(axis= 0 )["Price"]
mean_x,mean_y

(10.0, 13.0)

In [5]:
df["Deviations(x)"]=df["Diameter"]-mean_x
df["Deviations(y)"]=df["Price"]-mean_y

In [6]:
df["Product_of_dev"] = df["Deviations(x)"]*df["Deviations(y)"]

In [7]:
df

   Diameter  Price  Deviations(x)  Deviations(y)  Product_of_dev
0         8     10           -2.0           -3.0             6.0
1        10     13            0.0            0.0             0.0
2        12     16            2.0            3.0             6.0

In [8]:
sum_product_dev = df.sum(numeric_only=True)["Product_of_dev"]
sum_product_dev

12.0

In [9]:
df["Square_of_dev_x"]=df["Deviations(x)"]**2

In [10]:
df

,Diameter,Price,Deviations(x),Deviations(y),Product_of_dev,Square_of_dev_x
0,8,10,-2.0,-3.0,6.0,4.0
1,10,13,0.0,0.0,0.0,0.0
2,12,16,2.0,3.0,6.0,4.0

In [11]:
sum_sq_of_dev_x= df.sum(numeric_only=True)["Square_of_dev_x"]

In [14]:
slope = sum_product_dev/sum_sq_of_dev_x
slope

1.5

In [15]:
x = int(input("Enter Diameter: "))
b = mean_y - slope * mean_x
output = slope*x+b
output

Enter Diameter: 20

28.0