In [1]:
import numpy as np

In [21]:
print(board)

[['N' 'N' 'N']
 ['N' 'N' 'N']
 ['N' 'N' 'N']]

In [34]:
class Board:
    def __init__(self):
        self.board = np.array([["N"]*3]*3)
    
    def add_x_y(self,pos,val):
        if pos > (2,2) or pos < (0,0):
            return None
        x,y=pos
        if val == "X":
            self.board[x][y] = 'X'
        elif val=="Y":
            self.board[x][y] = "O"

class tick_tack_toe:
    def __init__(self,players_name):
        self.board = Board()
        self.players = players_name
        if len(self.players) > 2:
            self.players=players_name[:2]
        self.p1=self.players[0]
        self.p2=self.players[1]
    
    def display_board(self):
        pass

In [35]:
l= [1,2,3,4,5,6]
l2 = l[:2]

In [36]:
l2

[1, 2]

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:

df = pd.DataFrame({
    "Diameter": [8, 10, 12],
    "Price": [10, 13, 16]
})

In [29]:
mean_x,mean_y= df.mean(axis= 0 )["Diameter"],df.mean(axis= 0 )["Price"]

In [30]:
mean_x,mean_y

(10.0, 13.0)

In [33]:
df["Deviations(x)"]=df["Diameter"]-mean_x
df["Deviations(y)"]=df["Price"]-mean_y

In [36]:
df["Product_of_dev"] = df["Deviations(x)"]*df["Deviations(y)"]

In [37]:
df

   Diameter  Price  Deviations(x)  Deviations(y)  Product_of_dev
0         8     10           -2.0           -3.0             6.0
1        10     13            0.0            0.0             0.0
2        12     16            2.0            3.0             6.0

In [41]:
sum_product_dev = df.sum(numeric_only=True)["Product_of_dev"]
sum_product_dev

12.0

In [43]:
df["Square_of_dev_x"]=df["Deviations(x)"]**2

In [44]:
df

,Diameter,Price,Deviations(x),Deviations(y),Product_of_dev,Square_of_dev_x
0,8,10,-2.0,-3.0,6.0,4.0
1,10,13,0.0,0.0,0.0,0.0
2,12,16,2.0,3.0,6.0,4.0

In [46]:
sum_sq_of_dev_x= df.sum(numeric_only=True)["Square_of_dev_x"]

In [57]:
slope = sum_product_dev/sum_sq_of_dev_x
slope

1.5

In [60]:
x = int(input("Enter Diameter: "))
b = mean_y - slope * mean_x
output = slope*x+b
output

Enter Diameter: 30

43.0